---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 30m0s
  timeout: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.28.2
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 12h0m0s
  values:
    replicaCount: 1
    monitoring:
      grafanaDashboard:
        create: false
      podMonitorEnabled: false
