---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-db
  namespace: coder
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 20Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-db-app
  monitoring:
    enablePodMonitor: false
