apiVersion: v1
data:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:Cg90ovIltisa2gVvrSwIUA==,iv:jcrhkdz+0EjOQu1NeAhJ35z/9kKywU+HKtG2S66Gk00=,tag:8NOhaPmJ91cAcnkmkoP+yA==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:CVEe/409h6ZvRV2ImGri189MfIZI/3+jZP0Lck3yZufb4+GdSMRcBk3rQkHYen5W29HZ7ddBm0it6gueiegifChjXOpuorMh/C5Fau6yOCjDYkKTPqDWCg==,iv:WvimzEvfiZfO+a+e7qPGUaJYs4D1WcT44kPBpqWFxkU=,tag:93yX0wR/Jbaxcxi0vA5tzg==,type:str]
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: rustfs
sops:
    age:
        - recipient: age18sl2qhm4ja8l2q22t7h6ktmlz2zvc32mmj9ezeqt42f40g4crdpsrfyy09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WVVPZGhuclp2S0c4YWhu
            YUU4L2FBQndJdHZTR0hXUHVLWFRaNGUxRjJBClRKY0ljU2FTOXpLTWhVM0NmWTNL
            Z2srTmpEcXpObDVycHB2bVk3QXplQk0KLS0tIHh6MmNQVy8rZWRFa1A1enJ2bXc4
            dE5CaGdqS24zM0x3UmF5MUFSb3VSbEkKHLCwiqbGaa4W07tIgUMjqBu8WyuzLsme
            HrQjco4iF8Q468mp34b6P0Pc9PSp1wFTu9UNB2tnsm1GbEJXOt83RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-06T22:10:13Z"
    mac: ENC[AES256_GCM,data:sAOkkMJfj295qWvD/BRae4sYA0f7/+xKRulSb2RPWvbLittN5z2/RcmGEw/YwgXFSPdGHUo0QrN4oGbDAAwbVGl5kdrBVP1CMHryxeTZ8M7DSVT6ductS/PJ8KRfynYCRzKlZbgHnHa6k3g9NeW2uBmCDfTJmFfxv+7yjOT5k1Y=,iv:iFeZHKtLh/k7LyKAcEXO9CrmgIVz2BJO/5Lxa0WbqJ0=,tag:mId3+76qxTtv+bDK3mskvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
