apiVersion: v1
kind: Secret
metadata:
    name: kasm-db-app
    namespace: kasm
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ar+PF3uAPg==,iv:6KNbn4posvJxTJL7TrNNC0O4pCD6xDWxt/QpwHWSsGQ=,tag:/Jdak8OiT7WeiN4fXwmvgg==,type:str]
    password: ENC[AES256_GCM,data:JL4VpGpi7IbpaAi+jnbiGf0pf8CLJKKeaH4bTLRgtI5p1C5tyIeWIw==,iv:7GIF2Hv7vfBeOJjBgPLyL+9rGg/cVy7fQ0YZhbtOAHI=,tag:TZW7A3S0Cm79yYva5IpElA==,type:str]
sops:
    age:
        - recipient: age18sl2qhm4ja8l2q22t7h6ktmlz2zvc32mmj9ezeqt42f40g4crdpsrfyy09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWjlZYzZ2YWZNUDRDa0o5
            WmhFRDlCL1dacjlNRzV1STVUcDVkM3MvM3prCnQrdks5SGVKY2FCbUViQ3laWnlu
            MGE0WURnb3FkdmkwOUZvWXRLeFF3MHMKLS0tIFgrWitPV2JtcG1GUHhoVmpEQm9i
            R2g2OHhIRDBIMkhhR080K3RZdGNNUGcK3oidCNu/ft+iTo7eC6BQJyrtmJSJUi61
            eivCoRkZ5w95uKEtyw3f9ZjthDWDMfXOH2gkhHolP5uq0Mr+uA701A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T00:40:39Z"
    mac: ENC[AES256_GCM,data:9snBBGEBmEfMc0p9zbRn77m73Knev5k9RoRBFcA2hzbycDgVjmdT1HZzQ2Mk95csHfPgNm3rdDxVcXbJc0KLe1o3olp5qiDXJrvRuZmQRy+2RiT7l4xAgLVye3xmWGUR1+au3bQQjK6kXhXKPGvruu6TyXPqZiVUZlUEwLaxXg8=,iv:bPGqkmMf94pa1NWXkO58U37JaYI26zjtJuxPb7zYTBg=,tag:eoT/H4D1Ow1oU7puuqlv3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
