---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kasm-db
  namespace: kasm
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  enableSuperuserAccess: true
  superuserSecret:
    name: kasm-db-superuser
  storage:
    size: 20Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: kasm
      owner: kasmapp
      secret:
        name: kasm-db-app
  monitoring:
    enablePodMonitor: false
