apiVersion: v1
kind: Secret
metadata:
    name: baby-monitor-config
    namespace: baby-monitor
type: Opaque
stringData:
    BABY_MONITOR_ACCESS_TOKEN: ENC[AES256_GCM,data:y8tLQwFHVSNq,iv:YUhHuRlwF44M+84ieBh3TsbzKLmPVHz5WVAOEYP8PJ0=,tag:XoKP+fbibsBXplw8tmNN7A==,type:str]
    BABY_MONITOR_CAMERAS_JSON: ENC[AES256_GCM,data:C9QZB83vSMu5wFhJby+kAwI46R9X+/33JZ5cnC+Ojm6CXfYJWPgMVHMI37OzYi90giEdI6g9XHKbeU2adM6VwWfPEg3mHShS/nDWTK0Yln/IZSf6+g4hKQuV8i1OgbwIKIDq9to1tWM8uNw4oz9EQldAehpZcctnvXs9tPCoKL527yDOC92tEl83xtF9bMgDiPMHpc1+QIBWbdhnSWLksjwyPGWwu+/YOb51v61XeeQSrBWmcSLT21fw6nN9/QDP5BAfLt8Q+zZU3bqjpPUqzg==,iv:6wGuey3XokOGGtyVGMw2ZB+1l53ZLSohA7c6fY9/bjw=,tag:O/YKobWCJJJYn7JgpCQOEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnODQ1Y3FGT0pkTSt3Z3N3
            S3dsWGpJdjEwdXlrNHg0NzVjdW9wdWRsblQwCis1YlhSd3JQenRXVWE2dXdEVEh1
            Q2VFMHpENVk3SDJoVGxST1UxWnJsY2sKLS0tIFgxRnRJTXFWSW0xTVFFbVNGZUdX
            MTduZ1h6ZFgzY3ZhZGpLOHZJMFNRT0EKOtvv6cQAbxayhWs2XCzbtP5TfnX0nQFc
            Vchci8lDvSld2o7wvxU35Ok62oGXIosF8g+tGk8nQIG96j5KRC4dMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18sl2qhm4ja8l2q22t7h6ktmlz2zvc32mmj9ezeqt42f40g4crdpsrfyy09
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T05:57:43Z"
    mac: ENC[AES256_GCM,data:meJ+2sd3gd5BBbvZpydweXvAc9yTl5cQzAbeWop22x438QqERLKVPuqFjZnZe5Md+8kwEE4Gbg8X3fYZ0GhVPGxvTjPsbSP53THGo1sk4LsN7h1fNnt/lqhgAEzLXEShOWGqiEtezo0pPy4lhW8anu+TpYGQy2xWzmXU/ocSo14=,iv:WHAaeWuTte8PlVbcWvFlei2YQE/ZRcpjXy7SQTXb6VQ=,tag:Si3Za8oxutzMVBpQ6/EOrQ==,type:str]
    version: 3.13.1
