---
apiVersion: v1
kind: ConfigMap
metadata:
  name: baby-monitor-edge-nginx
  namespace: baby-monitor
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      if ($http_x_forwarded_proto = "http") {
        return 308 https://$host$request_uri;
      }

      location / {
        proxy_pass http://baby-monitor.baby-monitor.svc.cluster.local:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }
    }
