---
apiVersion: v1
kind: Service
metadata:
  name: baby-monitor-edge
  namespace: baby-monitor
  labels:
    app.kubernetes.io/name: baby-monitor-edge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: baby-monitor-edge
  ports:
    - name: http
      port: 80
      targetPort: http
