---
k3s_cluster:
  children:
    server:
      hosts:
        um890:
          ansible_host: 192.168.10.21
          nodeclass: large
          storageclass: fast
        ryzen5600:
          ansible_host: 192.168.10.22
          nodeclass: medium
          storageclass: fast
        n100:
          ansible_host: 192.168.10.23
          nodeclass: small
          storageclass: resilient
    agent:
      hosts: {}
