---
k3s_cluster:
  children:
    server:
      hosts:
        lab-bosgame:
          ansible_host: 192.168.32.69
          mac_address: 4c:50:dd:3d:8f:14
          nodeclass: medium
          storageclass: fast
    agent:
      hosts: {}
host_prep_hosts:
  hosts:
    lab-um890:
      ansible_host: 192.168.32.41
      ansible_user: lab
      ansible_port: 22
      mac_address: 3c:c5:dd:02:d5:a2
      host_prep_manage_hostname: true
      host_prep_disable_swap: true
      host_prep_disable_sleep: true
      host_prep_kernel_cmdline_args:
        - nvme_core.default_ps_max_latency_us=0
      host_prep_create_hushlogin: true
      host_prep_remove_bashrc_lines:
        - '^\. <\(k3s completion bash\).*# Added by k3s-ansible$'
        - '^export KUBECONFIG=~/.kube/config # Added by k3s-ansible$'
        - '^\. <\(kubectl completion bash\).*# Added by k3s-ansible$'
remote_agent_dev_hosts:
  hosts:
    lab-um890: {}
tts_pipeline_hosts:
  hosts:
    lab-um890: {}
