---
k3s_cluster:
  children:
    server:
      hosts:
        lab-node-1:
          ansible_host: TODO
          mac_address: 58:47:ca:7b:8a:5d
          nodeclass: large
          storageclass: fast
        lab-node-2:
          ansible_host: TODO
          mac_address: e8:ff:1e:d4:26:8b
          nodeclass: medium
          storageclass: fast
        lab-node-3:
          ansible_host: TODO
          mac_address: 1c:69:7a:c7:6f:f3
          nodeclass: medium
          storageclass: fast
    agent:
      hosts:
        lab-node-4:
          ansible_host: TODO
          mac_address: 84:47:09:2f:48:9a
          nodeclass: small
          storageclass: resilient
