---
- name: Install systemd exporter
  ansible.builtin.apt:
    name: "{{ systemd_exporter_package_name }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install systemd exporter service
  ansible.builtin.template:
    src: prometheus-systemd-exporter.service.j2
    dest: /etc/systemd/system/prometheus-systemd-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Enable systemd exporter
  ansible.builtin.systemd:
    name: "{{ systemd_exporter_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
