---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana-admin.sops.yaml
  - grafana-helm-values.sops.yaml
  - alertmanager-ntfy.sops.yaml
  - grafana-dashboard-uptime-nodes.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - grafana-ingress.yaml
  - alertmanager-ntfy.yaml
